CREATE OR ALTER VIEW dbo.vw_CaseAging
AS
SELECT
    Status,
    Days0To15 = SUM(CASE WHEN DATEDIFF(day, CreatedDate, COALESCE(ClosedDate, SYSUTCDATETIME())) BETWEEN 0 AND 15 THEN 1 ELSE 0 END),
    Days16To30 = SUM(CASE WHEN DATEDIFF(day, CreatedDate, COALESCE(ClosedDate, SYSUTCDATETIME())) BETWEEN 16 AND 30 THEN 1 ELSE 0 END),
    Days31To60 = SUM(CASE WHEN DATEDIFF(day, CreatedDate, COALESCE(ClosedDate, SYSUTCDATETIME())) BETWEEN 31 AND 60 THEN 1 ELSE 0 END),
    Days61Plus = SUM(CASE WHEN DATEDIFF(day, CreatedDate, COALESCE(ClosedDate, SYSUTCDATETIME())) >= 61 THEN 1 ELSE 0 END),
    TotalCases = COUNT_BIG(*)
FROM dbo.CaseFiles
WHERE IsDeleted = 0
GROUP BY Status;
GO
